name: Run Bash Script Manually

on:
  push:
    branches:
      - master
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Give execute permission to script
      run: chmod +x res/update-chnlist.sh

    - name: Run bash script
      run: bash res/update-chnlist.sh

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add chnlist.json
        git commit -m "Update chnlist.json"
        git push
