name: Run Bash Script Manually

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Give execute permission to script
      run: chmod +x res/update-chnlist.sh

    - name: Compare and update chnlist.txt
      run: |
        # 如果没有 chnlist.txt 文件的历史版本，复制一个新版本
        if [ ! -f chnlist_previous.txt ]; then
          cp chnlist.txt chnlist_previous.txt
        fi
        
        bash res/update-chnlist.sh
        
        # 比较新旧文件，只有文件内容有变化才提交
        if ! cmp -s chnlist.txt chnlist_previous.txt; then
          echo "File has changed, committing the updated chnlist.txt..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add chnlist.txt
          git commit -m "Update chnlist.txt"
          git push
        else
          echo "No changes in chnlist.txt, skipping commit."
        fi

    - name: Save previous version for next run
      run: |
        cp chnlist.txt chnlist_previous.txt
