name: Run Bash Script Manually

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Give execute permission to script
      run: chmod +x res/update-chnlist.sh

    - name: Run bash script
      run: bash res/update-chnlist.sh

    - name: Install sing-box
      run: bash <(curl -fsSL https://sing-box.app/deb-install.sh)

    - name: Compile chnlist.json to SRS format
      run: sing-box rule-set compile chnlist.json -o chnlist.srs

    - name: Compile adblock.json to SRS format
      run: sing-box rule-set compile adblock.json -o adblock.srs

    - name: Compile adblock.json to SRS format
      run: sing-box rule-set compile vod.json -o vod.srs

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add chnlist.json adblock.json chnlist.srs adblock.srs vod.srs
        git commit -m "Update chnlist.json and adblock.json, chnlist.srs and adblock.srs and vod.srs"
        git push
