name: Run Bash Script Daily

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run bash script
      run: bash res/update-chnlist.sh
