name: Run Bash Script Manually

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Give execute permission to script
      run: chmod +x res/update-chnlist.sh

    - name: Run bash script
      run: bash res/update-chnlist.sh

    - name: Check output file
      run: cat chnlist.txt
