name: Run Bash Script Manually

on:
  # 暂时移除定时任务，改为手动触发和 push 触发
  push:
    branches:
      - master  # 当代码提交到 master 分支时触发
  workflow_dispatch:  # 手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run bash script
      run: bash res/update-chnlist.sh
